<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnyfzen\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnyfzen/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnyfzen.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnyfzen\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKnyfzen\App_KernelDevDebugContainer([
    'container.build_hash' => 'Knyfzen',
    'container.build_id' => 'dc13099a',
    'container.build_time' => 1697768811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnyfzen');
